import { IStyleTimeLine } from "@/domain/types/components/time-line/type-style-time-line";

export const styleTimeLine: IStyleTimeLine ={
  dot:`
    grow-0
    w-6
    h-6
    rounded-full
    bg-tertiary
    border-4
    border-[#604229]
  `,
  startLine: `
    grow
    bg-gradient-to-b
    from-primary/50
    from-1%
    via-dark 
    via-100%
    w-3
    h-[125px]
    md:bg-gradient-to-r
    md:w-5/12
    md:h-4  
  `,
  endLine:`  
    grow
    rounded-t-lg
    bg-gradient-to-b
    from-primary
    from-1%
    via-primary/50 
    via-100% 
    w-3
    h-[125px]
    sm:rounded-t-lg
    sm:bg-gradient-to-b
    md:rounded-l-lg
    md:rounded-r-none
    md:bg-gradient-to-r
    md:w-5/12
    md:h-4
  `,
  wrapper:`
    flex
    justify-center
    items-center
    gap-1
    h-full
    sm:h-full 
    flex-col
    sm:flex-col
    md:flex-row
    md:w-full
    `
}